functionality:
  name: encrypt_cellranger
  namespace: cellranger
  version: "dev"
  description: "Encrypt a Cell Ranger archive"
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input archive
      example: input.tar.gz
    - name: "--password"
      alternatives: ["-p"]
      type: string
      description: Password
      example: foo
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      example: output.tar.gz
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: "ubuntu:21.04"
    setup:
      - type: apt
        packages: [ unzip, zip ]