functionality:
  name: build_bclconvert
  namespace: bclconvert
  description: "A helper script to download BCL Convert."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      type: file
      description: Zip file containing BCL convert rpm.
      default: "bcl-convert.rpm"
    - name: "--tag"
      type: string
      description: Name of the resulting Docker image.
      default: ghcr.io/data-intuitive/bclconvert:latest
      multiple: true
      multiple_sep: ','
    - name: "--push"
      type: boolean_true
      description: Whether or not to try to push the image to the corresponding registry.
  resources:
    - type: bash_script
      path: script.sh
    - path: Dockerfile
platforms:
  - type: native