functionality:
  name: download_cellranger_atac
  namespace: cellranger_atac
  version: "dev"
  description: "A helper script to download Cell Ranger ATAC."
  authors:
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ author ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  arguments:
    - name: "--tag"
      type: string
      description: Version of Cell Ranger ATAC to use.
      default: latest
    - name: "--timeout"
      type: integer
      description: Timeout in seconds.
      default: 600
    - name: "--multiplier"
      type: double
      description: Wait multiplier.
      default: 1
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      default: "cellranger_atac_${VIASH_PAR_TAG}.tar.gz"
  resources:
    - type: python_script
      path: script.py
platforms:
  - __merge__: ["/src/base/base_download_docker_platform.yaml"]
