functionality:
  name: download_bcl2fastq
  namespace: bcl2fastq
  version: "dev"
  description: "A helper script to download bcl2fastq."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--email"
      type: string
      description: Illumina account
      required: true
      example: foo@bar.com
    - name: "--password"
      type: string
      description: Password for Illumina account
      required: true
      example: mysecurepassword
    - name: "--timeout"
      type: integer
      description: Timeout in seconds.
      default: 600
    - name: "--multiplier"
      type: double
      description: Wait multiplier.
      default: 1
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      default: "bcl2fastq2.zip"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "ubuntu:21.04"
    setup:
      - type: apt
        packages: [ python3, firefox, python3-pip, curl ]
      - type: python
        packages: [ selenium, requests ]
      - type: docker
        run: 
          - curl -sSLO https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz &&
            tar zxf geckodriver-*.tar.gz &&
            mv geckodriver /usr/bin &&
            rm geckodriver-*.tar.gz
          #- update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          - ln -sf /usr/bin/python3 /usr/bin/python
