functionality:
  name: download_bcl2fastq
  namespace: bcl2fastq
  version: "dev"
  description: "A helper script to download bcl2fastq."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--email"
      type: string
      description: Illumina account
      required: true
      example: foo@bar.com
    - name: "--password"
      type: string
      description: Password for Illumina account
      required: true
      example: mysecurepassword
    - name: "--timeout"
      type: integer
      description: Timeout in seconds.
      default: 600
    - name: "--multiplier"
      type: double
      description: Wait multiplier.
      default: 1
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      default: "bcl2fastq.zip"
  resources:
    - type: python_script
      path: script.py
platforms:
  - __merge__: ["/src/base/base_download_docker_platform.yaml"]