functionality:
  name: download_spaceranger
  namespace: spaceranger
  version: "dev"
  description: "A helper script to download Space Ranger."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--tag"
      type: string
      description: Version of Space Ranger to use.
      default: latest
    - name: "--timeout"
      type: integer
      description: Timeout in seconds.
      default: 600
    - name: "--multiplier"
      type: double
      description: Wait multiplier.
      default: 1
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      default: "spaceranger_${VIASH_PAR_TAG}.tar.gz"
    - name: "--gh_token"
      type: string
      required: false
      description: "Token to authenticate to github with basis read permissions."
  resources:
    - type: python_script
      path: script.py
platforms:
  - __merge__: ["/src/base/base_download_docker_platform.yaml"]
