functionality:
  name: download_spaceranger
  namespace: spaceranger
  version: "dev"
  description: "A helper script to download Space Ranger."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--tag"
      type: string
      description: Version of Space Ranger to use.
      default: latest
    - name: "--timeout"
      type: integer
      description: Timeout in seconds.
      default: 600
    - name: "--multiplier"
      type: double
      description: Wait multiplier.
      default: 1
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      description: Output filename.
      default: "spaceranger_${VIASH_PAR_TAG}.tar.gz"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "ubuntu:20.04"
    setup:
      - type: apt
        packages: [ python3, firefox, python3-pip, curl ]
      - type: python
        packages: [ selenium, requests ]
      - type: docker
        run: 
          - curl -sSLO https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz &&
            tar zxf geckodriver-*.tar.gz &&
            mv geckodriver /usr/bin &&
            rm geckodriver-*.tar.gz
          #- update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          - ln -sf /usr/bin/python3 /usr/bin/python
