functionality:
  name: build_cellranger
  namespace: cellranger
  description: "A helper script to download Cell Ranger."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Encrypted zip file containing Cell Ranger.
      default: "cellranger.zip"
    - name: "--tag"
      type: string
      description: Name of the resulting Docker image.
      default: ghcr.io/data-intuitive/cellranger:latest
      multiple: true
      multiple_sep: ','
    - name: "--push"
      type: boolean_true
      description: Whether or not to try to push the image to the corresponding registry.
  resources:
    - type: bash_script
      path: script.sh
    - path: Dockerfile
    - path: mount.sh
platforms:
  - type: native