name: bcl2fastq-build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version of the tool to download
        required: true
      latest:
        description: Whether to mark the image as latest
        type: boolean
        required: true

jobs:
  bcl2fastq-build:
    env:
      base_name: ghcr.io/data-intuitive/bcl2fastq
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v3

    - name: Set up sbt
      uses: olafurpg/setup-scala@v13

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Build dependending containers
      run: |
        bin/viash_build -q 'bcl2fastq'

    - name: Download bcl2fastq
      run: |
        echo "Error: allow passing version number to component"
        exit 1
        bin/viash run src/bcl2fastq/download_bcl2fastq/config.vsh.yaml -- \
          --email "${{ secrets.ILLUMINA_EMAIL }}" \
          --password "${{ secrets.ILLUMINA_PASSWORD }}" \
          --output "bcl2fastq.zip" \
          --multiplier 2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Build image
      run: |
        version="${{ github.event.inputs.version }}"
        tag=$base_name:$version
        if [[ "${{ github.event.inputs.version }}" == "latest" ]]; then
          tag="$tag,$base_name:latest"
        bin/viash run src/bcl2fastq/build_bcl2fastq/config.vsh.yaml -- \
          --input "bcl2fastq.zip" \
          --tag "$tag" \
          --push

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
