name: bcl2fastq-build

on:
  push:
    branches: [ main ]

jobs:
  bcl2fastq-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {version: "3.10", tag: "ghcr.io/data-intuitive/bcl2fastq:2.20,ghcr.io/data-intuitive/bcl2fastq:latest"}

    steps:
    - uses: actions/checkout@v2

    - name: Set up sbt
      uses: olafurpg/setup-scala@v10

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Build dependending containers
      run: |
        bin/viash_build -q 'bcl2fastq'

    - name: Download bcl2fastq
      run: |
        bin/viash run src/bcl2fastq/download_bcl2fastq/config.vsh.yaml -- \
          --email "${{ secrets.ILLUMINA_EMAIL }}" \
          --password "${{ secrets.ILLUMINA_PASSWORD }}" \
          --output "bcl2fastq.zip" \
          --multiplier 2

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Build image
      run: |
        bin/viash run src/bcl2fastq/build_bcl2fastq/config.vsh.yaml -- \
          --input "bcl2fastq.zip" \
          --tag "${{ matrix.config.tag }}" \
          --push

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
