name: bclconvert-build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version of the tool to download
        required: true
      latest:
        description: Whether to mark the image as latest
        type: boolean
        required: true
      push: 
        description: Whether or not to push the image
        type: boolean
        required: true

jobs:
  bclconvert-build:
    env:
      base_name: ghcr.io/data-intuitive/bclconvert
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v4

    - name: Build dependending containers
      run: |
        viash ns build -q 'bclconvert'

    - name: Download BCL Convert
      run: |
        echo "Error: allow passing version number to component"
        exit 1
        viash run src/bclconvert/download_bclconvert/config.vsh.yaml -- \
          --email "${{ secrets.ILLUMINA_EMAIL }}" \
          --password "${{ secrets.ILLUMINA_PASSWORD }}" \
          --output "bclconvert.rpm" \
          --multiplier 2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GTHB_PAT }}
        
    - name: Build image
      run: |
        if [ ${{ github.event.inputs.push }} == 'true' ]; then
          should_push=1
        fi
        version="${{ github.event.inputs.version }}"
        tag=$base_name:$version
        if [[ "${{ github.event.inputs.version }}" == "latest" ]]; then
          tag="$tag,$base_name:latest"
        viash run src/bclconvert/build_bclconvert/config.vsh.yaml -- \
          --input "bclconvert.rpm" \
          --tag "$tag" ${should_push:+--push}