name: cellranger-arc-build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version of the tool to download
        required: true
      latest:
        description: Whether to mark the image as latest
        type: boolean
        required: true
      push: 
        description: Whether or not to push the image
        type: boolean
        required: true

jobs:
  cellranger-arc-build:
    env:
      base_name: ghcr.io/data-intuitive/cellranger_arc
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v4

    - name: Build dependending containers
      run: |
        viash ns build -q 'bcl2fastq|cellranger_arc'

    - name: Download Cell Ranger ARC
      run: |
        viash run src/cellranger_arc/download_cellranger_arc/config.vsh.yaml -- \
          --tag "${{ github.event.inputs.version }}" \
          --output "cellranger_arc.tar.gz" \
          --multiplier 2

    - name: Download bcl2fastq
      run: |
        viash run src/bcl2fastq/download_bcl2fastq/config.vsh.yaml -- \
          --email "${{ secrets.ILLUMINA_EMAIL }}" \
          --password "${{ secrets.ILLUMINA_PASSWORD }}" \
          --output "bcl2fastq.zip" \
          --multiplier 2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GTHB_PAT }}
        
    - name: Build image
      run: |
        if [ ${{ github.event.inputs.push }} == 'true' ]; then
          should_push=1
        fi
        version="${{ github.event.inputs.version }}"
        tag=$base_name:$version
        if [[ "${{ github.event.inputs.version }}" == "latest" ]]; then
          tag="$tag,$base_name:latest"
        viash run src/cellranger_arc/build_cellranger_arc/config.vsh.yaml -- \
          --input_cellranger_arc "cellranger_arc.tar.gz" \
          --input_bcl2fastq "bcl2fastq.zip" \
          --tag "$tag" ${should_push:+--push}