name: spaceranger-build

on:
  push:
    branches: [ main ]

jobs:
  spaceranger-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {version: "1.0", tag: "ghcr.io/data-intuitive/spaceranger:1.0"}
        - {version: "1.1", tag: "ghcr.io/data-intuitive/spaceranger:1.1"}
        - {version: "1.2", tag: "ghcr.io/data-intuitive/spaceranger:1.2"}
        - {version: "1.3", tag: "ghcr.io/data-intuitive/spaceranger:1.3,ghcr.io/data-intuitive/spaceranger:latest"}

    steps:
    - uses: actions/checkout@v2

    - name: Set up sbt
      uses: olafurpg/setup-scala@v10

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Build dependending containers
      run: |
        bin/viash_build -q 'bcl2fastq|spaceranger'

    - name: Download Space Ranger
      run: |
        bin/viash run src/spaceranger/download_spaceranger/config.vsh.yaml -- \
          --tag "${{ matrix.config.version }}" \
          --output "spaceranger.tar.gz" \
          --multiplier 2

    - name: Download bcl2fastq
      run: |
        bin/viash run src/bcl2fastq/download_bcl2fastq/config.vsh.yaml -- \
          --email "${{ secrets.ILLUMINA_EMAIL }}" \
          --password "${{ secrets.ILLUMINA_PASSWORD }}" \
          --output "bcl2fastq.zip" \
          --multiplier 2

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GTHB_PAT }}
        
    - name: Build image
      run: |
        bin/viash run src/spaceranger/build_spaceranger/config.vsh.yaml -- \
          --input_spaceranger "spaceranger.tar.gz" \
          --input_bcl2fastq "bcl2fastq.zip" \
          --tag "${{ matrix.config.tag }}" \
          --push

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
